spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/NGAdmin
    username: sa
    password: sa
    driver-class-name: oracle.jdbc.driver.OracleDriver
    maxWait: 10000
    initial-size: 10
    max-active: 30
    min-idle: 10