//-----------------------------------------------------------------------
// <Copyright file="BizUser.cs" company="RuYiAdmin">
// * Copyright (C) 2022 RuYiAdmin All Rights Reserved
// * Version : 4.0.30319.42000
// * Author  : auto generated by RuYiAdmin T4 Template
// * FileName: BizUser.cs
// * History : Created by RuYiAdmin 01/19/2022 09:01:54
// </Copyright>
//-----------------------------------------------------------------------

using NGProjectAdmin.Common.Class.Excel;
using NGProjectAdmin.Entity.Base;
using SqlSugar;
using System;
using System.ComponentModel.DataAnnotations;

namespace NGProjectAdmin.Entity.BusinessEntity.BusinessModule
{
    /// <summary>
    /// BizUser Entity Model
    /// </summary>   
    //[Serializable]
    [SugarTable("biz_user")]
    public class BizUser : NGAdminBaseEntity
    {
        /// <summary>
        /// 用户登录账号
        /// </summary>
        [Required]
        [MaxLength(128)]
        [SugarColumn(ColumnName = "USER_LOGON_NAME")]
        public String UserLogonName { get; set; }

        /// <summary>
        /// 用户名称
        /// </summary>
        [Required]
        [MaxLength(128)]
        [SugarColumn(ColumnName = "USER_DISPLAY_NAME")]
        public String UserDisplayName { get; set; }

        /// <summary>
        /// 用户密码
        /// </summary>
        [Required]
        [MaxLength(512)]
        [SugarColumn(ColumnName = "USER_PASSWORD")]
        public String UserPassword { get; set; }

        /// <summary>
        /// 座机
        /// </summary>
        //[Required]
        [MaxLength(45)]
        [SugarColumn(ColumnName = "TELEPHONE")]
        public String Telephone { get; set; }

        /// <summary>
        /// 手机
        /// </summary>
        //[Required]
        [MaxLength(45)]
        [SugarColumn(ColumnName = "MOBILEPHONE")]
        public String MobilePhone { get; set; }

        /// <summary>
        /// 邮箱
        /// </summary>
        //[Required]
        [MaxLength(45)]
        [SugarColumn(ColumnName = "EMAIL")]
        public String Email { get; set; }

        /// <summary>
        /// 是否启用
        /// 0：禁用；
        /// 1：启用
        /// </summary>
        [SugarColumn(ColumnName = "IS_ENABLED")]
        public int IsEnabled { get; set; }

        /// <summary>
        /// 性别
        /// 0：男
        /// 1：女
        /// 2：第三性别
        /// </summary>
        [Required]
        [SugarColumn(ColumnName = "SEX")]
        [ExcelExport("性别", "0:男,1:女,2:第三性别")]
        [ExcelImport("性别", "男:0,女:1,第三性别:2")]
        public int Sex { get; set; }

        /// <summary>
        /// 盐
        /// </summary>
        [Required]
        [SugarColumn(ColumnName = "SALT")]
        public Guid Salt { get; set; }

        /// <summary>
        /// 预留字段1
        /// </summary>
        [SugarColumn(ColumnName = "EXTEND1")]
        public String Extend1 { get; set; }

        /// <summary>
        /// 预留字段2
        /// </summary>
        [SugarColumn(ColumnName = "EXTEND2")]
        public String Extend2 { get; set; }

        /// <summary>
        /// 预留字段3
        /// </summary>
        [SugarColumn(ColumnName = "EXTEND3")]
        public String Extend3 { get; set; }

        /// <summary>
        /// 预留字段4
        /// </summary>
        [SugarColumn(ColumnName = "EXTEND4")]
        public String Extend4 { get; set; }

        /// <summary>
        /// 预留字段5
        /// </summary>
        [SugarColumn(ColumnName = "EXTEND5")]
        public String Extend5 { get; set; }
    }
}
