
//-----------------------------------------------------------------------
// <Copyright file="ISysRecordService.cs" company="RuYiAdmin">
// * Copyright (C) 2022 RuYiAdmin All Rights Reserved
// * Version : 6.0.8
// * Author  : auto generated by RuYiAdmin Template Code Generator
// * FileName: ISysRecordService.cs
// * History : Created by RuYiAdmin 2022/8/23 9:16:38
// </Copyright>
//-----------------------------------------------------------------------

using NGProjectAdmin.Entity.BusinessEntity.SystemManagement;
using NGProjectAdmin.Service.Base;

namespace NGProjectAdmin.Service.BusinessService.SystemManagement.RecordService
{
    /// <summary>
    /// SysRecord业务层接口
    /// </summary>   
    public interface ISysRecordService : INGAdminBaseService<SysRecord>
    {
    }
}
