
//-----------------------------------------------------------------------
// <Copyright file="SysRecordService.cs" company="RuYiAdmin">
// * Copyright (C) 2022 RuYiAdmin All Rights Reserved
// * Version : 6.0.8
// * Author  : auto generated by RuYiAdmin Template Code Generator
// * FileName: SysRecordService.cs
// * History : Created by RuYiAdmin 2022/8/23 9:16:38
// </Copyright>
//-----------------------------------------------------------------------

using NGProjectAdmin.Entity.BusinessEntity.SystemManagement;
using NGProjectAdmin.Repository.BusinessRepository.SystemManagement.RecordRepository;
using NGProjectAdmin.Service.Base;

namespace NGProjectAdmin.Service.BusinessService.SystemManagement.RecordService
{
    /// <summary>
    /// SysRecord业务层实现
    /// </summary>
    public class SysRecordService : NGAdminBaseService<SysRecord>, ISysRecordService
    {
        /// <summary>
        /// 仓储实例
        /// </summary>
        private readonly ISysRecordRepository SysRecordRepository;

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="SysRecordRepository"></param>
        public SysRecordService(ISysRecordRepository SysRecordRepository) : base(SysRecordRepository)
        {
            this.SysRecordRepository = SysRecordRepository;
        }
    }
}
