//-----------------------------------------------------------------------
// <Copyright file=" SysRoleOrg.cs" company="RuYiAdmin">
// * Copyright (C) 2021 RuYiAdmin All Rights Reserved
// * Version : 4.0.30319.42000
// * Author  : auto generated by RuYiAdmin T4 Template
// * FileName: SysRoleOrg.cs
// * History : Created by RuYiAdmin 11/08/2021 10:01:36
// </Copyright>
//-----------------------------------------------------------------------

using NGProjectAdmin.Entity.Base;
using SqlSugar;
using System;
using System.ComponentModel.DataAnnotations;

namespace NGProjectAdmin.Entity.BusinessEntity.SystemManagement
{
    /// <summary>
    /// 角色机构关系模型
    /// </summary>   
    [SugarTable("sys_role_org")]
    public class SysRoleOrg : NGAdminBaseEntity
    {
        /// <summary>
        /// 角色编号
        /// </summary>
        [Required]
        [SugarColumn(ColumnName = "ROLE_ID")]
        public Guid RoleId { get; set; }

        /// <summary>
        /// 机构编号
        /// </summary>
        [Required]
        [SugarColumn(ColumnName = "ORG_ID")]
        public Guid OrgId { get; set; }

        /// <summary>
        /// 类型：0，自有；1，继承
        /// </summary>
        [Required]
        [SugarColumn(ColumnName = "OWNER_TYPE")]
        public int OwnerType { get; set; }
    }
}
