
//-----------------------------------------------------------------------
// <Copyright file="SysRecord.cs" company="RuYiAdmin">
// * Copyright (C) 2022 RuYiAdmin All Rights Reserved
// * Version : 6.0.8
// * Author  : auto generated by RuYiAdmin Template Code Generator
// * FileName: SysRecord.cs
// * History : Created by RuYiAdmin 2022/8/23 9:16:38
// </Copyright>
//-----------------------------------------------------------------------

using NGProjectAdmin.Entity.Base;
using SqlSugar;
using System;

namespace NGProjectAdmin.Entity.BusinessEntity.SystemManagement
{
    /// <summary>
    /// SysRecord 实体模型
    /// </summary>   
    [Serializable]
    [SugarTable("sys_record")]
    public class SysRecord : NGAdminBaseEntity
    {

    }
}
