//-----------------------------------------------------------------------
// <Copyright file="ISysRoleOrgService.cs" company="RuYiAdmin">
// * Copyright (C) 2021 RuYiAdmin All Rights Reserved
// * Version : 4.0.30319.42000
// * Author  : auto generated by RuYiAdmin T4 Template
// * FileName: ISysRoleOrgService.cs
// * History : Created by RuYiAdmin 11/08/2021 10:23:17
// </Copyright>
//-----------------------------------------------------------------------

using NGProjectAdmin.Entity.BusinessEntity.SystemManagement;
using NGProjectAdmin.Service.Base;
using System.Threading.Tasks;

namespace NGProjectAdmin.Service.BusinessService.SystemManagement.RoleOrgService
{
    /// <summary>
    /// 角色机构业务层接口
    /// </summary>   
    public interface IRoleOrgService : INGAdminBaseService<SysRoleOrg>
    {
        /// <summary>
        /// 加载角色与机构缓存
        /// </summary>
        Task LoadSystemRoleOrgCache();

        /// <summary>
        /// 清理角色与机构缓存
        /// </summary>
        Task ClearSystemRoleOrgCache();
    }
}
